# Generated by Django 5.2.11 on 2026-02-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_strayreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strayreport',
            name='image',
        ),
        migrations.AddField(
            model_name='strayreport',
            name='area',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='strayreport',
            name='district',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='strayreport',
            name='dog_count',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='strayreport',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='strayreport',
            name='local_body',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='strayreport',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='strayreport',
            name='reporter_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='strayreport',
            name='reporter_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='strayreport',
            name='reporter_phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='strayreport',
            name='state',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='strayreport',
            name='urgency',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='strayreport',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Resolved', 'Resolved')], default='Pending', max_length=20),
        ),
    ]
