# Generated by Django 5.2.11 on 2026-03-03 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_strayreport_image_strayreport_area_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StrayReport',
        ),
    ]
